# This is a basic workflow to help you get started with Actions

name: yuque-sync-cron

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  schedule:
    # 北京时间每天凌晨5点
    - cron: '0 21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GH_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set node env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Set env variable && Run start
        env:
          YUQUE_USER_TOKEN: ${{ secrets.YUQUE_USER_TOKEN }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPOS: ${{ secrets.YUQUE_REPOS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_LOGIN: ${{ secrets.GH_LOGIN }}
          GH_REPO: ${{ secrets.GH_REPO }}
        run: npm run start
